import Head from 'next/head'
import Image from 'next/image'
import s from '../styles/Home.module.css'
import {InfoCards} from "../components/InfoCards/InfoCards";
import {PropsWithChildren} from "react";
import Link from "next/link";

export type HomeProps = {
    cards: any,
};

export default function Home(props: PropsWithChildren<HomeProps>) {
  const {
      cards,
  } = props;

  return (
    <div className={s.container}>
      <Head>
        <title>Testing Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href={'/server'} className={s.link}>Server-side rendering</Link>
      <main className={s.main}>
        <h1 className={s.title}>Изучаем Next.js, Static Generation</h1>
        <InfoCards cards={cards}/>
      </main>

      <footer className={s.footer}>

      </footer>
    </div>
  )
}

export const getStaticProps = async (context) => {
  const response = await fetch('https://gorest.co.in/public/v2/posts');
  const cards = await response.json();
  return {
      props: {cards},
  }
}
